import Foundation

struct LoggedRun: Identifiable, Codable, Sendable {
    let id: UUID? // Optional, generated by DB
    let userId: UUID? // Optional, handled by Auth
    let runDate: Date
    let distanceKm: Double
    let durationMinutes: Double
    let calories: Double?
    let avgPace: String?
    let avgHeartRate: Int?
    let elevationGain: Int?
    let feedback: String?
    let createdAt: Date? // Optional, generated by DB
    /// Full HealthKit-derived analytics + route polyline. Persisted as JSONB
    /// in `logged_runs.analytics_blob` so the run's charts and route follow
    /// the user's account across devices instead of being trapped on the
    /// device that recorded the workout.
    let analyticsBlob: RunAnalyticsBlob?

    enum CodingKeys: String, CodingKey {
        case id
        case userId = "user_id"
        case runDate = "run_date"
        case distanceKm = "distance_km"
        case durationMinutes = "duration_minutes"
        case calories
        case avgPace = "avg_pace"
        case avgHeartRate = "avg_heart_rate"
        case elevationGain = "elevation_gain"
        case feedback
        case createdAt = "created_at"
        case analyticsBlob = "analytics_blob"
    }

    // Standard Initializer
    init(
        id: UUID? = nil,
        userId: UUID? = nil,
        runDate: Date,
        distanceKm: Double,
        durationMinutes: Double,
        calories: Double? = nil,
        avgPace: String? = nil,
        avgHeartRate: Int? = nil,
        elevationGain: Int? = nil,
        feedback: String? = nil,
        createdAt: Date? = nil,
        analyticsBlob: RunAnalyticsBlob? = nil
    ) {
        self.id = id
        self.userId = userId
        self.runDate = runDate
        self.distanceKm = distanceKm
        self.durationMinutes = durationMinutes
        self.calories = calories
        self.avgPace = avgPace
        self.avgHeartRate = avgHeartRate
        self.elevationGain = elevationGain
        self.feedback = feedback
        self.createdAt = createdAt
        self.analyticsBlob = analyticsBlob
    }

    // Older rows in Supabase don't have `analytics_blob` — make decoding
    // tolerant of its absence so existing runs keep loading.
    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try c.decodeIfPresent(UUID.self, forKey: .id)
        self.userId = try c.decodeIfPresent(UUID.self, forKey: .userId)
        self.runDate = try c.decode(Date.self, forKey: .runDate)
        self.distanceKm = try c.decode(Double.self, forKey: .distanceKm)
        self.durationMinutes = try c.decode(Double.self, forKey: .durationMinutes)
        self.calories = try c.decodeIfPresent(Double.self, forKey: .calories)
        self.avgPace = try c.decodeIfPresent(String.self, forKey: .avgPace)
        self.avgHeartRate = try c.decodeIfPresent(Int.self, forKey: .avgHeartRate)
        self.elevationGain = try c.decodeIfPresent(Int.self, forKey: .elevationGain)
        self.feedback = try c.decodeIfPresent(String.self, forKey: .feedback)
        self.createdAt = try c.decodeIfPresent(Date.self, forKey: .createdAt)
        self.analyticsBlob = try c.decodeIfPresent(RunAnalyticsBlob.self, forKey: .analyticsBlob)
    }
}
